SELECT *
FROM USER
WHERE ID = 11;

SELECT *
FROM ITEM
WHERE ID = (
  SELECT ID_ITEM
  FROM ORDER_ITEM
  WHERE ID_ORDER = (
    -- Todos los pedidos hechos por el user 10
    SELECT ID_ORDER
    FROM USER_ORDER
    WHERE ID_USER = 10
  )
);

SELECT *
FROM ITEM
WHERE ID = (
  SELECT ID_ITEM
  FROM ORDER_ITEM
  WHERE ID_ORDER = (
    SELECT ID_ORDER
    FROM USER_ORDER
    WHERE ID_USER = 10
  )
);

SELECT U.NAME, I.NAME
FROM USER U, ITEM I, ORDER_ITEM OI, USER_ORDER UO
WHERE U.ID = UO.ID_USER AND UO.ID_ORDER = OI.ID_ORDER AND OI.ID_ITEM = I.ID;
