SELECT *
FROM USER
WHERE ID = 11;

SELECT *
FROM ITEM
WHERE ID = (
  SELECT ID_ITEM
  FROM ORDER_ITEM
  WHERE ID_ORDER = (
    -- Todos los pedidos hechos por el user 10
    SELECT ID_ORDER
    FROM USER_ORDER
    WHERE ID_USER = 10
  )
);

SELECT *
FROM ITEM
WHERE ID = (
  SELECT ID_ITEM
  FROM ORDER_ITEM
  WHERE ID_ORDER IN (
    -- Pedidos hechos por el usuario 10
    SELECT ID_ORDER
    FROM USER_ORDER
    WHERE ID_USER = 10
  )
);

SELECT *
FROM U_O
WHERE ;

SELECT UO.ID_ORDER, U.NAME, I.NAME, C.NAME, I.NAME, I.PRIZE
FROM USER U, ITEM I, ORDER_ITEM OI, USER_ORDER UO, CATEGORY C
WHERE U.ID = UO.ID_USER AND UO.ID_ORDER = OI.ID_ORDER AND OI.ID_ITEM = I.ID AND C.ID = I.ID_CATEGORY AND U.ID = ?
ORDER BY UO.ID_ORDER, I.NAME;

SELECT *, COUNT(*)
FROM ITEM
WHERE ID IN (
  SELECT ID_ITEM
  FROM ORDER_ITEM
  WHERE ID_ORDER = 6
)
GROUP BY ID;

SELECT OI.ID_ORDER AS OI_ID_ORDER, OI.ID_ITEM AS OI_ID_ITEM, U.ID AS U_ID
FROM ORDER_ITEM OI, USER U, USER_ORDER UO
WHERE OI.ID_ORDER = UO.ID_ORDER AND U.ID = UO.ID_USER AND OI.ID_ORDER = 6

SELECT *
FROM USER_ORDER
WHERE ID_USER = ?;

* from
