CREATE TABLE `USER`(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE `ORDER`(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE `USER_ORDER`(
  ID_USER INTEGER,
  ID_ORDER INTEGER,
  FOREIGN KEY (ID_USER) REFERENCES `USER`(ID),
  FOREIGN KEY (ID_ORDER) REFERENCES `ORDER`(ID)
);

INSERT INTO USER_ORDER VALUES(1, 1);

CREATE TABLE `CATEGORY`(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

CREATE TABLE `ITEM`(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PRIZE INTEGER,
  ID_CATEGORY INTEGER,
  FOREIGN KEY (ID_CATEGORY) REFERENCES `CATEGORY`(ID)
);

CREATE TABLE `ORDER_ITEM`(
  ID_ORDER INTEGER,
  ID_ITEM INTEGER,
  FOREIGN KEY (ID_ORDER) REFERENCES `ORDER`(ID),
  FOREIGN KEY (ID_ITEM) REFERENCES `ITEM`(ID)
);

INSERT INTO CATEGORY VALUES (1, 'Periféricos');
INSERT INTO CATEGORY(NAME) VALUES ('Placa base');
INSERT INTO CATEGORY(NAME) VALUES ('CPU');
INSERT INTO CATEGORY(NAME) VALUES ('RAM');
INSERT INTO CATEGORY(NAME) VALUES ('Memorias flash');
INSERT INTO CATEGORY(NAME) VALUES ('Tarjetas gráficas');

INSERT INTO USER (NAME, PASSWORD) VALUES ('César', '1234');

INSERT INTO ITEM (NAME, PRIZE, ID_CATEGORY) VALUES ('Razer Naga', 89.99 * 100, 1);
INSERT INTO ITEM (NAME, PRIZE, ID_CATEGORY) VALUES ('Razer Blackwidows', 101.99 * 100, 1);
INSERT INTO ITEM (NAME, PRIZE, ID_CATEGORY) VALUES ('Asus X6', 51.99 * 100, 2);

INSERT INTO ORDER VALUES (1);

INSERT INTO ORDER_ITEM VALUES (1, 1);
INSERT INTO ORDER_ITEM VALUES (1, 2);

SELECT I.NAME, I.PRIZE / 100, C.NAME
FROM ITEM I, CATEGORY C
WHERE I.ID_CATEGORY = C.ID
ORDER BY I.PRIZE;
