package es.cesalberca.mercato.view;

import es.cesalberca.mercato.controller.auth.Login;
import es.cesalberca.mercato.controller.database.DatabaseConnector;
import es.cesalberca.mercato.model.User;
import static es.cesalberca.mercato.view.JFApp.dbh;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 * Modal para el inicio de sesión.
 * @author Cesar
 */
public class JPLogin extends javax.swing.JPanel {
    protected static User user = null;
    
    public JPLogin() {
        initComponents();
    }
    
    /**
     * Genera un modal con usuario y contraseña.
     * @param jbAddOrder Botón que se desactiva cuando se inicie sesión correctamente.
     */
    public static void login(JButton jbAddOrder){
        JTextField jtfUser = new JTextField(5);
        JTextField jtfPassword = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Usuario:"));
        myPanel.add(jtfUser);
        myPanel.add(Box.createHorizontalStrut(15));
        myPanel.add(new JLabel("Contraseña:"));
        myPanel.add(jtfPassword);

        // Captura el resultado del click del usuario.
        int result = JOptionPane.showConfirmDialog(null, myPanel, "Inicio de sesión", JOptionPane.OK_CANCEL_OPTION);
        
        if (result == JOptionPane.OK_OPTION) {
            User userTryingToLogin = new User(jtfUser.getText(), jtfPassword.getText());
            try {
                
                // Comprobamos que el usuario y la contraseña son válidas.
                if (Login.isValidUser(userTryingToLogin)) {
                    // Buscamos el id de ese usuario
                    int userId = ((User) dbh.search(DatabaseConnector.getConnection(), userTryingToLogin)).getId();;
//                    user = new User(userId, userTryingToLogin.getName(), userTryingToLogin.getPassword());
                    JOptionPane.showMessageDialog(null, "Bienvenido");
                    jbAddOrder.setEnabled(true);
                    // Cuando el usuario se loggea con éxito se instancia el gestor de la tienda.
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectas.");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JPLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
