/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cesalberca.mercato.view;

import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Cesar
 */
public class JPSignup extends javax.swing.JPanel {

    /**
     * Creates new form JPSignup
     */
    public JPSignup() {
        initComponents();
    }
    
    public static void signup(){
      JTextField username = new JTextField(5);
      JTextField password = new JTextField(5);
      JTextField confirmPassword = new JTextField(5);
      

      JPanel myPanel = new JPanel();
      myPanel.add(new JLabel("Usuario:"));
      myPanel.add(username);
      myPanel.add(Box.createHorizontalStrut(15)); // a spacer
      myPanel.add(new JLabel("Contraseña:"));
      myPanel.add(password);
      myPanel.add(new JLabel("Confirmar contraseña:"));
      myPanel.add(confirmPassword);

      int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Registrar usuario", JOptionPane.OK_CANCEL_OPTION);
      if (result == JOptionPane.OK_OPTION) {
         System.out.println("x value: " + username.getText());
         System.out.println("y value: " + password.getText());
      }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
